### ISSUE TITLE
chore: Add `checkbox-labels.js` from `design-system`

### ISSUE THREAD

**Issue by DDubuc1** [gc-proto/experimental#17]
js/checkbox-labels.js
js/demo-toggles.js
js/resize-iframe.js

these files have been marked to be moved to GC-Proto experimental

link to EN repo : https://github.com/canada-ca/design-system/issues/145

**Comment by jmealing** [comment]
I've confirmed files are good to move to experimental

**Comment by delisma** [comment]
Only `js/checkbox-label.js` needs to be moved to `gc-proto/experimental`.
`js/demo-toggle.js` needs to be added to `gc-proto/systeme-conception`.
`js/resize-iframe.js` needs to be added to `gc-proto/systeme-conception`.

Related to https://github.com/canada-ca/systeme-conception/issues/83 and https://github.com/canada-ca/design-system/issues/145
