### ISSUE TITLE
chore: Add `coded-layout/images/ip-cover-image-1200x726.jpg`

### ISSUE THREAD

**Issue by DDubuc1** [gc-proto/experimental#7]
Hello, 

coded-layout/images/ip-cover-image-1200x726.jpg has been marked to be moved to gc-proto

link to issue in EN repo

**Comment by delisma** [comment]
@DDubuc1 This wasn't flagged to be added in this repo. It was flagged to be added in the `canada-ca\systeme-conception` repo only.
